/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'peter' at '1/13/14 6:30 AM' with Gradle 1.9
 *
 * @author peter, @date 1/13/14 6:30 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
